server:
  port: 3000
  servlet:
    context-path: ${CONTEXT_PATH:/api}
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:postgresql://${HOST:localhost}:${PORT:5400}/${DATABASE_NAME:parcel_tracker_db}
    database-platform: org.postgresql.Driver
    username: ${DB_USERNAME:admin}
    password: ${PASSWORD:teasAdmin}
    type: com.zaxxer.hikari.HikariDataSource
    pool-name: nps_HikariCP
    initial-size: ${POSTGRES_INIT_SIZE:1}
    minimum-idle: ${POSTGRES_MIN_SIZE:1}
    maximum-pool-size: ${POSTGRES_POOL_SIZE:10}
    auto-commit: true
    idle-timeout: ${POSTGRES_IDLE_TIMEOUT:30000}
    connection-test-query: SELECT 1
    max-lifetime: ${POSTGRES_MAX_LIFE_TIME:180000}
    connection-timeout: ${POSTGRES_CONN_TIMIEOUT:30000}
  application:
    name: parcel-tracker
  main:
    allow-bean-definition-overriding: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: update
    show-sql: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
application:
  snowflake:
    data-center: 1